application: signin
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /scholarshipstyle\.css
  static_files: scholarshipstyle.css
  upload: favicon\.css

- url: /.*
  script: signin.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
